# Generated by Django 3.0.6 on 2020-05-17 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accompaniment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnglishName', models.CharField(max_length=128)),
                ('SecondName', models.CharField(max_length=128)),
                ('PricePurchase', models.FloatField()),
                ('PriceSell', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Surname', models.CharField(max_length=128)),
                ('Phone', models.CharField(max_length=16)),
                ('RegisterData', models.DateTimeField(auto_now_add=True)),
                ('LastLoginDate', models.DateTimeField(auto_now=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color', models.CharField(max_length=7)),
                ('LastLoginDate', models.DateTimeField(auto_now=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnglishName', models.CharField(max_length=128)),
                ('SecondName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street', models.CharField(max_length=128)),
                ('HouseName', models.CharField(max_length=128)),
                ('Flat', models.CharField(max_length=128)),
                ('Floor', models.CharField(max_length=128)),
                ('Comment', models.TextField()),
                ('AddingDate', models.DateTimeField(auto_now_add=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeliveryPrice', models.FloatField()),
                ('PurchasePrice', models.FloatField()),
                ('SalePrice', models.FloatField()),
                ('LimitPerOrder', models.SmallIntegerField()),
                ('DarkKitchen', models.BooleanField()),
                ('ImgPopup', models.ImageField(upload_to='uploads/img/popup/')),
                ('ImgMenuPage', models.ImageField(upload_to='uploads/img/menu_page/')),
                ('Accompaniments', models.ManyToManyField(to='api.Accompaniment')),
            ],
        ),
        migrations.CreateModel(
            name='DishTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnglishName', models.CharField(max_length=128)),
                ('SecondName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnglishName', models.CharField(max_length=128)),
                ('SecondName', models.CharField(max_length=128)),
                ('Value', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PayType', models.CharField(max_length=128)),
                ('PayInfo', models.CharField(max_length=128)),
                ('TipsCount', models.FloatField()),
                ('TotalCost', models.FloatField()),
                ('DeliveryCost', models.FloatField()),
                ('AddingDate', models.DateTimeField(auto_now_add=True)),
                ('OnWhenDate', models.DateTimeField()),
                ('DeliveredDate', models.DateTimeField()),
                ('Status', models.CharField(max_length=128)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
                ('CourierTakedMoney', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Courier')),
                ('DeliveryAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.DeliveryAddress')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Price', models.FloatField()),
                ('SalePrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnglishName', models.CharField(max_length=128)),
                ('SecondName', models.CharField(max_length=128)),
                ('Address', models.CharField(max_length=512)),
                ('CoordinatesLongtitude', models.FloatField()),
                ('CoordinatesLatitude', models.FloatField()),
                ('Phone', models.CharField(max_length=16)),
                ('DiscountGiven', models.BooleanField()),
                ('StandartCookingTime', models.SmallIntegerField()),
                ('MoreInfoEnglish', models.TextField()),
                ('MoreInfoSecond', models.TextField()),
                ('SeoSectionEnglish', models.TextField()),
                ('SeoSectionSecond', models.TextField()),
                ('Type', models.CharField(max_length=12)),
                ('SliderImgBigEng', models.ImageField(upload_to='uploads/img/eng/big/')),
                ('SliderImgSmallEng', models.ImageField(upload_to='uploads/img/eng/small/')),
                ('SliderImgBigSecond', models.ImageField(upload_to='uploads/img/second/big/')),
                ('SliderImgSmallSecond', models.ImageField(upload_to='uploads/img/second/small')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantSectionMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnglishName', models.CharField(max_length=128)),
                ('SecondName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Taxe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnglishName', models.CharField(max_length=128)),
                ('SecondName', models.CharField(max_length=128)),
                ('ValuePercent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DaysOfWeek', models.CharField(max_length=128)),
                ('StartTime', models.CharField(max_length=128)),
                ('StopTime', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnglishName', models.CharField(max_length=128)),
                ('SecondName', models.CharField(max_length=128)),
                ('PricePurchase', models.FloatField()),
                ('PriceSell', models.FloatField()),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='SectionMenus',
            field=models.ManyToManyField(to='api.RestaurantSectionMenu'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='TypesOfCusine',
            field=models.ManyToManyField(to='api.CuisineType'),
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuyPrice', models.FloatField()),
                ('SellPrice', models.FloatField()),
                ('Discount', models.FloatField()),
                ('AddingDate', models.DateTimeField(auto_now_add=True)),
                ('SendToRestourantDate', models.DateTimeField(auto_now=True)),
                ('RestourantConfirmDate', models.DateTimeField(auto_now=True)),
                ('RestourantDoneDate', models.DateTimeField(auto_now=True)),
                ('CourierTakedDate', models.DateTimeField(auto_now=True)),
                ('CourierDeliveredDate', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(max_length=128)),
                ('Courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Courier')),
                ('Dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Dish')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant')),
                ('Taxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Taxe')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='TimePeriod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.TimePeriod'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BattaryCharge', models.SmallIntegerField()),
                ('LastLoginDate', models.DateTimeField(auto_now=True)),
                ('Restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='Modifications',
            field=models.ManyToManyField(to='api.Modification'),
        ),
        migrations.AddField(
            model_name='dish',
            name='Packages',
            field=models.ManyToManyField(to='api.Package'),
        ),
        migrations.AddField(
            model_name='dish',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='Tags',
            field=models.ManyToManyField(to='api.DishTag'),
        ),
        migrations.AddField(
            model_name='dish',
            name='Taxe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Taxe'),
        ),
        migrations.AddField(
            model_name='dish',
            name='TimePeriod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.TimePeriod'),
        ),
        migrations.AddField(
            model_name='dish',
            name='Toppings',
            field=models.ManyToManyField(to='api.Topping'),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardToken', models.CharField(max_length=256)),
                ('CardType', models.CharField(max_length=128)),
                ('LastFourDigits', models.CharField(max_length=4)),
                ('AddingDate', models.DateTimeField(auto_now_add=True)),
                ('ExpireDate', models.DateTimeField()),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Client')),
            ],
        ),
        migrations.AddField(
            model_name='accompaniment',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant'),
        ),
    ]
