# Generated by Django 3.0.6 on 2020-05-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='DiscountGiven',
            field=models.FloatField(),
        ),
    ]
