# Generated by Django 3.0.6 on 2020-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200519_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='isClient',
            field=models.BooleanField(default=True),
        ),
    ]
