# Generated by Django 3.0.6 on 2020-05-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200519_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='Restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Restaurant'),
        ),
    ]
