# Generated by Django 3.0.6 on 2020-05-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200520_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='CourierTakedMoney',
            new_name='Courier',
        ),
        migrations.AlterField(
            model_name='courier',
            name='LastLoginDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='manager',
            name='LastLoginDate',
            field=models.DateTimeField(),
        ),
    ]
