# Generated by Django 3.0.6 on 2020-05-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200522_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Courier',
        ),
        migrations.AddField(
            model_name='order',
            name='Couriers',
            field=models.ManyToManyField(blank=True, to='api.Courier'),
        ),
    ]
