# Generated by Django 3.0.6 on 2020-05-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200522_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='TimePeriod',
        ),
        migrations.AddField(
            model_name='order',
            name='TimePeriod',
            field=models.ManyToManyField(to='api.TimePeriod'),
        ),
    ]
