# Generated by Django 3.0.6 on 2020-05-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200522_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='CookingTime',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
